version: "3"

services:
  postgres:
    image: "postgres:10"
    volumes:
      - postgres:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.2
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"  
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash start_jobs.sh
    volumes:
      - .:/encontre-me
      - gems:/gems

  app:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/encontre-me
      - gems:/gems


volumes:
  postgres:
  gems:
  es-data:
    driver: local
  redis:
